import { jsPDF } from "jspdf";

export interface ReportData {
  title: string;
  scope: string;
  clientName?: string;
  dateStr: string;
  metrics: { label: string; value: string | number }[];
  summary: string;
}

export async function generateReportPDF(data: ReportData): Promise<File> {
  // We use standard A4 dimensions for jsPDF
  const doc = new jsPDF("p", "pt", "a4");

  const pageWidth = doc.internal.pageSize.getWidth();
  let cursorY = 50;

  // Header Background
  doc.setFillColor(79, 70, 229); // Indigo-600
  doc.rect(0, 0, pageWidth, 100, "F");

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text(data.title, 40, 55);

  // Subtitle / Date
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Scope: ${data.scope}   |   Date: ${data.dateStr}`, 40, 75);
  if (data.clientName) {
    doc.text(`Client: ${data.clientName}`, 40, 90);
  }

  // Reset text color
  doc.setTextColor(30, 41, 59); // Slate-800
  cursorY = 140;

  // Key Metrics Section
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Key Performance Metrics", 40, cursorY);
  cursorY += 30;

  // Draw metrics
  doc.setFontSize(11);
  const metricBoxWidth = (pageWidth - 100) / 3;
  let metricX = 40;

  data.metrics.forEach((m, index) => {
    if (index > 0 && index % 3 === 0) {
      cursorY += 50;
      metricX = 40;
    }
    
    doc.setFont("helvetica", "bold");
    doc.text(m.label, metricX, cursorY);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(14);
    doc.text(String(m.value), metricX, cursorY + 20);
    doc.setFontSize(11);

    metricX += metricBoxWidth + 10;
  });

  cursorY += 60;

  // Summary Section
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Executive Summary", 40, cursorY);
  cursorY += 25;

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  // Split text into lines to avoid overflow
  const splitText = doc.splitTextToSize(data.summary, pageWidth - 80);
  doc.text(splitText, 40, cursorY);

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184); // Slate-400
  doc.text("Generated by ThePieCraft CRM Automated Analyst", 40, doc.internal.pageSize.getHeight() - 40);

  // Convert to Blob and then File
  const pdfBlob = doc.output("blob");
  const fileName = `${data.title.replace(/[^a-zA-Z0-9]/g, "_")}_${Date.now()}.pdf`;
  
  return new File([pdfBlob], fileName, { type: "application/pdf" });
}
