"use client";

import { useEffect, useState } from "react";
import {
  ArrowRight,
  Calendar,
  Download,
  FileText,
  Filter,
  Search,
  Sparkles,
  TrendingUp,
  RefreshCw,
} from "lucide-react";
import {
  CartesianGrid,
  Legend,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import KpiCard from "@/components/KpiCard";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/Card";
import { PageHeader } from "@/components/ui/PageHeader";
import { getClientReports } from "@/app/actions/crm";

const performanceData = [
  { month: "Dec", roas: 2.4, ctr: 1.6 },
  { month: "Jan", roas: 2.8, ctr: 1.9 },
  { month: "Feb", roas: 3.1, ctr: 2.2 },
  { month: "Mar", roas: 3.6, ctr: 2.8 },
  { month: "Apr", roas: 3.9, ctr: 3.1 },
  { month: "May", roas: 4.2, ctr: 3.4 },
];

const typeVariant: Record<string, "portal" | "brand" | "warning" | "info" | "neutral"> = {
  Monthly: "portal",
  Quarterly: "brand",
  Custom: "warning",
  Project: "info",
  Audit: "neutral",
};

export default function ClientReportsPage() {
  const [reports, setReports] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");

  const fetchReports = async () => {
    setIsLoading(true);
    const res = await getClientReports();
    if (res && res.success && res.data) {
      setReports(res.data);
    }
    setIsLoading(false);
  };

  useEffect(() => {
    fetchReports();
  }, []);

  const handleDownloadPDF = (title: string) => {
    const blob = new Blob(
      [`${title}\n\nGenerated by ThePieCraft on ${new Date().toLocaleString()}.\n\nThis is a summary export. For the full formatted report, please contact your account manager.`],
      { type: "text/plain;charset=utf-8" }
    );
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.replace(/\s+/g, "-")}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const filteredReports = reports.filter(r => {
    const q = searchQuery.toLowerCase();
    const titleMatch = (r.name || "").toLowerCase().includes(q);
    return titleMatch;
  });

  const featuredReport = reports[0] || null;

  if (isLoading) {
    return (
      <div className="flex h-[80vh] items-center justify-center">
        <div className="flex flex-col items-center gap-4 text-slate-400">
          <RefreshCw className="h-8 w-8 animate-spin text-teal-500" />
          <p className="text-sm font-semibold tracking-wide uppercase">Syncing reports deck...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-fadeIn">
      <PageHeader
        eyebrow="Insights"
        title="Reports"
        description="Performance reports, audits, and deep-dives delivered by your account team."
        actions={
          <>
            <Button variant="outline" size="md">
              <Sparkles className="h-4 w-4" />
              Request analysis
            </Button>
            <Button variant="portal" size="md" onClick={() => featuredReport && handleDownloadPDF(featuredReport.name)}>
              <Download className="h-4 w-4" />
              Latest PDF
            </Button>
          </>
        }
      />

      <div className="grid grid-cols-2 xl:grid-cols-4 gap-4">
        <KpiCard
          title="Avg ROAS"
          value="4.2×"
          change="+0.3× MoM"
          changeType="positive"
          accent="portal"
          icon={<TrendingUp className="h-5 w-5" />}
        />
        <KpiCard
          title="CTR"
          value="3.4%"
          change="+0.3%"
          changeType="positive"
          accent="brand"
        />
        <KpiCard
          title="Conv. Rate"
          value="2.8%"
          change="+0.1%"
          changeType="positive"
          accent="emerald"
        />
        <KpiCard
          title="Reports Delivered"
          value={`${reports.length}`}
          change="Available in vault"
          changeType="neutral"
          accent="amber"
          icon={<FileText className="h-5 w-5" />}
        />
      </div>

      <Card>
        <CardHeader>
          <div>
            <CardTitle>Performance Trend</CardTitle>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
              ROAS (×) and CTR (%) across the last six months
            </p>
          </div>
          <div className="hidden sm:flex items-center gap-3 text-xs">
            <span className="inline-flex items-center gap-1.5 text-slate-600 dark:text-slate-300">
              <span className="h-2 w-2 rounded-full bg-teal-500" /> ROAS
            </span>
            <span className="inline-flex items-center gap-1.5 text-slate-600 dark:text-slate-300">
              <span className="h-2 w-2 rounded-full bg-indigo-500" /> CTR
            </span>
          </div>
        </CardHeader>
        <CardContent className="p-2 sm:p-4">
          <div className="h-72">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={performanceData} margin={{ top: 12, right: 16, left: -4, bottom: 0 }}>
                <CartesianGrid stroke="currentColor" strokeOpacity={0.08} vertical={false} />
                <XAxis dataKey="month" tickLine={false} axisLine={false} tick={{ fill: "currentColor", fontSize: 12, opacity: 0.6 }} />
                <YAxis tickLine={false} axisLine={false} tick={{ fill: "currentColor", fontSize: 12, opacity: 0.6 }} />
                <Tooltip
                  contentStyle={{ borderRadius: 12, border: "1px solid rgba(99,102,241,0.2)", background: "rgba(8,13,30,0.97)", fontSize: 12, boxShadow: "0 4px 24px rgba(0,0,0,0.4)" }}
                  labelStyle={{ color: "#94a3b8", fontWeight: 500 }}
                  itemStyle={{ color: "#ffffff", fontWeight: 600 }}
                />
                <Legend wrapperStyle={{ fontSize: 12, paddingTop: 8 }} iconType="circle" />
                <Line type="monotone" dataKey="roas" name="ROAS (×)" stroke="#14B8A6" strokeWidth={2.5} dot={{ r: 3, fill: "#14B8A6" }} />
                <Line type="monotone" dataKey="ctr" name="CTR (%)" stroke="#6366F1" strokeWidth={2.5} dot={{ r: 3, fill: "#6366F1" }} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </CardContent>
      </Card>

      {/* Featured + list */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <Card className="lg:col-span-1 overflow-hidden">
          <div className="relative h-32 bg-indigo-600 dark:bg-indigo-950/45 p-6 flex flex-col justify-end">
            <div className="absolute -top-6 -right-6 h-24 w-24 rounded-full bg-white/15 blur-2xl" />
            <div className="relative z-10">
              <Badge variant="portal" className="bg-white/15 text-white border border-white/20">
                Featured this month
              </Badge>
            </div>
          </div>
          <CardContent className="p-5">
            {featuredReport ? (
              <>
                <p className="text-base font-semibold text-slate-900 dark:text-white">
                  {featuredReport.name}
                </p>
                <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
                  Delivered {featuredReport.createdAt ? new Date(featuredReport.createdAt).toLocaleDateString("en-US", { month: "short", day: "numeric" }) : "Today"} • {featuredReport.size || "1.5 MB"}
                </p>
                <ul className="mt-4 space-y-2 text-sm text-slate-600 dark:text-slate-300">
                  <li className="flex items-start gap-2">
                    <span className="mt-1.5 h-1.5 w-1.5 rounded-full bg-indigo-500 shrink-0" />
                    ROAS remains healthy at 4.2×
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-1.5 h-1.5 w-1.5 rounded-full bg-indigo-500 shrink-0" />
                    Top campaign yield lead by lookalike scaling
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-1.5 h-1.5 w-1.5 rounded-full bg-indigo-500 shrink-0" />
                    Detailed conversion path and ROAS tables attached
                  </li>
                </ul>
                <div className="mt-5 flex gap-2">
                  <Button variant="portal" size="sm" onClick={() => handleDownloadPDF(featuredReport.name)}>
                    <Download className="h-3.5 w-3.5" /> Download
                  </Button>
                </div>
              </>
            ) : (
              <p className="text-sm text-slate-500 py-6 italic text-center">No reports featured yet.</p>
            )}
          </CardContent>
        </Card>

        <Card className="lg:col-span-2 overflow-hidden">
          <CardHeader>
            <CardTitle>All Reports</CardTitle>
            <div className="flex items-center gap-2">
              <div className="relative max-w-xs">
                <Search className="pointer-events-none absolute inset-y-0 left-3 h-full w-4 text-slate-400" />
                <input
                  type="search"
                  placeholder="Search reports…"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="h-9 w-48 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 pl-9 pr-3 text-sm placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-portal-500/40 text-slate-800 dark:text-white"
                />
              </div>
            </div>
          </CardHeader>
          <div className="divide-y divide-slate-100 dark:divide-slate-800">
            {filteredReports.map((r) => {
              const cat = r.name?.toLowerCase().includes("monthly") ? "Monthly" :
                          r.name?.toLowerCase().includes("quarterly") ? "Quarterly" :
                          r.name?.toLowerCase().includes("seo") || r.name?.toLowerCase().includes("audit") ? "Audit" : "Custom";
              return (
                <div key={r.id} className="flex items-center gap-3 p-4 sm:p-5 hover:bg-slate-50/60 dark:hover:bg-slate-900/40 transition-colors">
                  <div className="h-10 w-10 rounded-xl bg-portal-50 dark:bg-portal-500/10 text-portal-600 dark:text-portal-300 flex items-center justify-center shrink-0">
                    <FileText className="h-5 w-5" />
                  </div>
                  <div className="min-w-0 flex-1">
                    <p className="text-sm font-medium text-slate-900 dark:text-white truncate">{r.name}</p>
                    <div className="mt-1 flex items-center gap-2 flex-wrap text-xs text-slate-500 dark:text-slate-400">
                      <Badge variant={typeVariant[cat] ?? "neutral"}>{cat}</Badge>
                      <span className="inline-flex items-center gap-1">
                        <Calendar className="h-3 w-3" /> {r.createdAt ? new Date(r.createdAt).toLocaleDateString("en-US", { month: "short", day: "numeric" }) : "Today"}
                      </span>
                      <span className="hidden sm:inline">•</span>
                      <span className="hidden sm:inline tabular-nums">{r.size || "1.2 MB"}</span>
                    </div>
                  </div>
                  <Button variant="outline" size="sm" onClick={() => handleDownloadPDF(r.name)}>
                    <Download className="h-3.5 w-3.5" /> <span className="hidden sm:inline">PDF</span>
                  </Button>
                </div>
              );
            })}
            {filteredReports.length === 0 && (
              <p className="p-8 text-center text-xs text-slate-500 italic">No reports found.</p>
            )}
          </div>
        </Card>
      </div>
    </div>
  );
}
